name: Build single-file executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build single-file executable with PyInstaller
        run: |
          pyinstaller --onefile --name cb_query_tester \
            --hidden-import numpy \
            --hidden-import couchbase.cluster \
            --hidden-import couchbase.options \
            --hidden-import couchbase.n1ql \
            --hidden-import couchbase.auth \
            --hidden-import couchbase.exceptions \
            --hidden-import dns.resolver \
            cb_query_tester.py

      - name: Show dist contents
        run: |
          ls -al dist || dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cb_query_tester-${{ runner.os }}
          path: |
            dist/cb_query_tester*
          if-no-files-found: error
